DROP TABLE IF EXISTS customer;
DROP SEQUENCE IF EXISTS seq;
CREATE SEQUENCE seq START 1;

CREATE TABLE customer (
  id INTEGER PRIMARY KEY DEFAULT nextval('seq'),
  name VARCHAR NOT NULL ,
  age INTEGER NOT NULL ,
  mobile INTEGER NOT NULL UNIQUE
);